/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.simulator;

/**
 *
 * @author saad
 */
public class gui extends javax.swing.JFrame {

    /**
     * Creates new form gui
     */
    public gui() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"R0    (00000)", "r0  ", null},
                {"R1    (00001)", "at", null},
                {"R2    (00010)", "v0", null},
                {"R3    (00011)", "v1", null},
                {"R4    (00100)", "a0", null},
                {"R5    (00101)", "a1", null},
                {"R6    (00110)", "a2", null},
                {"R7    (00111)", "a3", null},
                {"R8    (01000)", "t0", "0x00000003"},
                {"R9    (01001)", "t1", "0x00000002"},
                {"R10 (01010)", "t2", null},
                {"R11 (01011)", "t3", null},
                {"R12 (01100)", "t4", null},
                {"R13 (01101)", "t5", null},
                {"R14 (01110)", "t6", null},
                {"R15 (01111)", "t7", null},
                {"R16 (10000)", "s0", null},
                {"R17 (10001)", "s1", null},
                {"R18 (10010)", "s2", null},
                {"R19 (10011)", "s3", null},
                {"R20 (10100)", "s4", null},
                {"R21 (10101)", "s5", null},
                {"R22 (10110)", "s6", null},
                {"R23 (10111)", "s7", null},
                {"R24 (11000)", "t8", null},
                {"R25 (11001)", "t9", null},
                {"R26 (11010)", "k0", null},
                {"R27 (11011)", "k1", null},
                {"R28 (11100)", "gp", null},
                {"R29 (11101)", "sp", null},
                {"R30 (11110)", "s8", null},
                {"R31 (11111)", "ra", null}
            },
            new String [] {
                "Number", "Register", "Value"
            }
        ));
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(150);
            jTable1.getColumnModel().getColumn(2).setPreferredWidth(100);
        }

        jLabel1.setText("PC");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        jLabel2.setText("Write you program here");

        jButton1.setText("Excute");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Excute all");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(79, 79, 79)
                        .addComponent(jButton2)
                        .addGap(84, 84, 84))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(103, 103, 103))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jTextField1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2)
                            .addComponent(jButton1)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(248, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>                        

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private int convertToDec(String str)
    {
        int res = 0, pow = 0;
        for(int i = str.length() - 1 ; i>=0 ; i--)
        {
            res += ( Character.getNumericValue(str.charAt(i)) * Math.pow(2, pow));
            pow++;
        }
        return res;
    }
    
    static private String convertToBinary(int x, int numOfBits)
    {
        String res = "";      
        res = Integer.toBinaryString(x);
        while(res.length() < numOfBits) res = '0' + res;
        return res;
    }
    static private String convertToHexa(int x, int numOfBits)
    {
        String res = "";      
        res = Integer.toHexString(x);
        while(res.length() < numOfBits) res = '0' + res;
        return res;
    }
    static private String subStr(int st, int ed, String str)
    {
        String res = "";
        for(int i = st ; i<ed ; i++)
        {
            res += str.charAt(i);
        }
        return res;
    }
    private int toExcute(String str)
    {
        int dst = 0;
      //  System.out.println(str.substring(26, 32));
        String opCode = str.substring(0, 6);
        if(opCode.equals("000000"))        //R-Type instructions
        {            
            //parse string
            String regDst = str.substring(6, 11);
            String reg1 = str.substring(11, 16);
            String reg2 = str.substring(16, 21);

            System.out.println("regDst = " + regDst);
            System.out.println("reg1 = " + reg1);
            System.out.println("reg2 = " + reg2);

            //Extract values from table
            String x1 = jTable1.getValueAt(convertToDec(reg1), 2).toString();
            String x2 = jTable1.getValueAt(convertToDec(reg2), 2).toString();

            //Remove 0x from the string
            x1 = x1.substring(2, x1.length());
            x2 = x2.substring(2, x2.length());

            //Convert hexa to decimal
            int num1 = Integer.parseInt(x1, 16);
            int num2 = Integer.parseInt(x2, 16);

            String instruction = str.substring(26, 32);
            int res = 0;
            //perform the operation
            if(instruction.equals("100000"))   //func : add
            {                    
                 res = num1 + num2;
            } 
            else if(instruction.equals("100010"))  //func : sub
            {
                 res = num1 - num2;
            }
            else if(instruction.equals("100100"))  //func : AND
            {
                 res = num1 & num2;
            }

            else if(instruction.equals("100101"))  //func : OR
            {
                 res = num1 | num2;
            }
            //convert decimal to hexa to save in table                
            String y = "0x" + convertToHexa(res, 8);

            //save in the table
            jTable1.setValueAt(y, convertToDec(regDst), 2);
        }
        else      //I-Type
        {
            String regDst = str.substring(6, 11);
            String reg1 = str.substring(11, 16);
            String imm = str.substring(16, 32); 
            
            System.out.println("regDst = " + regDst);
            System.out.println("reg1 = " + reg1);
            System.out.println("imm = " + imm);

            //Extract values from table
            String x1 = jTable1.getValueAt(convertToDec(reg1), 2).toString();

            //Remove 0x from the string
            x1 = x1.substring(2, x1.length());

            //Convert hexa to decimal
            int num1 = Integer.parseInt(x1, 16);
            int num2 = Integer.parseInt(imm, 2);
            System.out.println("num1 = " + num1);
            System.out.println("num2 = " + num2);
            int res = 0;
            //perform the operation
            if(opCode.equals("001000"))   //func : addi
            {                    
                 res = num1 + num2;
            }
            else if(opCode.equals("001100"))  //func : ANDi
            {
                 res = num1 & num2;
            }

            else if(opCode.equals("001101"))  //func : ORi
            {
                 res = num1 | num2;
            }
            //convert decimal to hexa to save in table                
            String y = "0x" + convertToHexa(res, 8);

            //save in the table
            jTable1.setValueAt(y, convertToDec(regDst), 2);
        }
        return dst;
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        toExcute(itype);
    }                                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        
        System.out.println(convertToBinary(9, 5));
//        String str2 = "00000001010010000100100000100000";
//        int x= toExcute(str2);
//        //System.out.println("x = " + x);

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gui().setVisible(true);
            }
        });
    }
    static String str = "00000001010010000100100000100100";
    static String itype = "00110101010010000000000000000100";
    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration                   
}
